title = "Qomarul Hasan"
baseURL = "https://qomarhsn.pages.dev/"
# theme = "FixIt"
defaultContentLanguage = "en"
languageCode = "en"
hasCJKLanguage = false
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150

ignoreLogs = [
  "error-get-remote-image",
  "error-get-remote-json",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken"
]

