# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------


[[main]]
  identifier = "about"
  parent = ""
  pre = ""
  post = ""
  name = "About"
  url = "/about"
  title = ""
  weight = 2
  [main.params]
    icon = "fa-solid fa-user-tie"

[[main]]
  identifier = "projects"
  parent = ""
  pre = ""
  post = ""
  name = "Project"
  url = "/projects"
  title = ""
  weight = 2
  [main.params]
    icon = "fa-solid fa-briefcase"

[[main]]
  identifier = "tags"
  parent = ""
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
  weight = 3
  [main.params]
    icon = "fa-solid fa-tags"
