version = "0.3.X"
description = "Explore technologies with a Linux & tech enthusiast. This blog offers programming tutorials, open‑source project insights, and practical tech tips."
keywords = ["Qomarul Hasan", "qomarhsn"]
defaultTheme = "dark"
fingerprint = ""
dateFormat = "2006-01-02"
images = []
enablePWA = true
externalIcon = false
capitalizeTitles = true
withSiteTitle = true
titleDelimiter = "-"
indexWithSubtitle = false
summaryPlainify = false
disableThemeInject = false

[author]
  name = "Qomarul Hasan"
  email = "mail@qomarhsn.com"
  link = "https://qomarhsn.com"
  avatar = "/profile.webp"

[gitInfo]
  repo = ""
  branch = "main"
  dir = "content"
  issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"

[app]
  title = "Qomarul Hasan"
  noFavicon = false
  svgFavicon = "/favicon.svg"
  iconColor = "#5bbad5"
  tileColor = "#da532c"

  [app.themeColor]
    light = "#f8f8f8"
    dark = "#252627"

[search]
  enable = true
  type = "fuse"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false

  [search.algolia]
    index = ""
    appID = ""
    searchKey = ""

  [search.fuse]
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

[header]
  desktopMode = "sticky"
  mobileMode = "auto"

  [header.title]
    logo = ""
    name = ""
    pre = ""
    post = ""
    typeit = true

  [header.subtitle]
    name = ""
    typeit = false

[breadcrumb]
  enable = false
  sticky = false
  showHome = false
  separator = "/"
  capitalize = true

[navigation]
  inSection = false
  reverse = false

[footer]
  enable = true
  copyright = true
  author = true
  since = 2025
  gov = ""
  icp = ""
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/ " target="_blank">CC BY-NC-SA 4.0</a>'

  [footer.powered]
    enable = false
    hugoLogo = false
    themeLogo = false

  [footer.siteTime]
    enable = false
    animate = true
    icon = "fa-solid fa-heartbeat"
    pre = ""
    value = ""

  [footer.order]
    powered = 0
    copyright = 0
    statistics = 0
    visitor = 0
    beian = 0

[archives]
  paginate = 20
  dateFormat = "01-02"

[section]
  paginate = 20
  dateFormat = "01-02"

  [section.feed]
    limit = -1
    fullText = false

[list]
  paginate = 20
  dateFormat = "01-02"

  [list.feed]
    limit = -1
    fullText = false

[recentlyUpdated]
  archives = true
  section = true
  list = true
  days = 30
  maxCount = 10

[tagcloud]
  enable = false
  min = 14
  max = 32
  peakCount = 10
  orderby = "name"

[home]
  [home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/profile.webp"
    avatarMenu = ""
    title = "Qomarul Hasan"
    subtitle = "Full-time learner and part-time Linux & tech enthusiast, currently mastering CSE fundamentals. On this blog, I share my journey, insights, and hands-on tips as I explore programming and technologies that make life easier."
    typeit = false
    social = true
    disclaimer = ""

  [home.posts]
    enable = true
    paginate = 10

[social]
  GitHub = "qomarhsn"
  Linkedin = ""
  Twitter = "qomarhsn"
  Instagram = ""
  Facebook = "qomarhsn"
  Telegram = "qomarhsn"
  Medium = ""
  Gitlab = ""
  Youtubelegacy = ""
  Youtubecustom = ""
  Youtubechannel = ""
  Tumblr = ""
  Quora = ""
  Keybase = ""
  Pinterest = ""
  Reddit = ""
  Codepen = ""
  FreeCodeCamp = ""
  Bitbucket = ""
  Stackoverflow = ""
  Weibo = ""
  Odnoklassniki = ""
  VK = ""
  Flickr = ""
  Xing = ""
  Snapchat = ""
  Soundcloud = ""
  Spotify = ""
  Bandcamp = ""
  Paypal = ""
  Fivehundredpx = ""
  Mix = ""
  Goodreads = ""
  Lastfm = ""
  Foursquare = ""
  Hackernews = ""
  Kickstarter = ""
  Patreon = ""
  Steam = ""
  Twitch = ""
  Strava = ""
  Skype = ""
  Whatsapp = ""
  Zhihu = ""
  Douban = ""
  Angellist = ""
  Slidershare = ""
  Jsfiddle = ""
  Deviantart = ""
  Behance = ""
  Dribbble = ""
  Wordpress = ""
  Vine = ""
  Googlescholar = ""
  Researchgate = ""
  Mastodon = ""
  Thingiverse = ""
  Devto = ""
  Gitea = ""
  XMPP = ""
  Matrix = ""
  Bilibili = ""
  ORCID = ""
  Liberapay = ""
  Ko-Fi = ""
  BuyMeaCoffee = ""
  Linktree = ""
  QQ = ""
  QQGroup = ""
  Diaspora = ""
  CSDN = ""
  Discord = "qomarhsn"
  DiscordInvite = ""
  Lichess = ""
  Pleroma = ""
  Kaggle = ""
  MediaWiki= ""
  Plume = ""
  HackTheBox = ""
  RootMe = ""
  Feishu = ""
  TryHackMe = ""
  Douyin = ""
  TikTok = ""
  Credly = ""
  Phone = ""
  Email = "mail@qomarhsn.com"
  RSS = false

[typeit]
  speed = 100
  cursorSpeed = 1000
  cursorChar = "|"
  duration = -1
  loop = false

[mermaid]
  themes = ["default", "dark"]

[admonition]

[taskList]

[repoVersion]
  url = "https://github.com/hugo-fixit/FixIt/releases/tag/v "
  name = "FixIt"

[pangu]
  enable = false
  selector = "article"

[watermark]
  enable = false
  content = ""
  opacity = 0.1
  width = 150
  height = 20
  rowSpacing = 60
  colSpacing = 30
  rotate = 15
  fontSize = 0.85
  fontFamily = "inherit"

[busuanzi]
  enable = false
  source = "https://vercount.one/js "
  siteViews = true
  pageViews = true

[verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""
  so = ""
  sogou = ""

[seo]
  image = ""
  thumbnailUrl = ""

[analytics]
  enable = false

  [analytics.google]
    id = ""
    anonymizeIP = true

  [analytics.fathom]
    id = ""
    server = ""

[cookieconsent]
  enable = false

  [cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

[cdn]
  data = ""

[compatibility]
  polyfill = false
  objectFit = false

[githubCorner]
  enable = false
  permalink = "https://github.com/hugo-fixit/FixIt "
  title = "View source on GitHub"
  position = "right"

[gravatar]
  enable = false
  host = "www.gravatar.com"
  style = ""

[backToTop]
  enable = true
  scrollpercent = false

[readingProgress]
  enable = true
  start = "left"
  position = "top"
  reversed = false
  light = ""
  dark = ""
  height = "2px"

[pace]
  enable = false
  color = "blue"
  theme = "minimal"

[feed]
  limit = 10
  fullText = true

  [feed.follow]
    feedId = ""
    userId = ""

[customPartials]
  head = [
    "inject/fixit-docs-bookmark.html",
  ]
  profile = []
  aside = []
  comment = []
  footer = []
  widgets = []
  assets = []
  postFooterBefore = []
  postFooterAfter = []

[dev]
  enable = false
  c4u = false

[page]
  authorAvatar = true
  hiddenFromHomePage = false
  hiddenFromSearch = false
  hiddenFromRelated = false
  hiddenFromFeed = false
  twemoji = false
  lightgallery = false
  ruby = true
  fraction = true
  fontawesome = true
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/ " target="_blank">CC BY-NC-SA 4.0</a>'
  linkToMarkdown = true
  linkToSource = true
  linkToEdit = true
  linkToReport = true
  pageStyle = "normal"
  autoBookmark = false
  wordCount = true
  readingTime = true
  endFlag = ""
  instantPage = false
  collectionList = true
  collectionNavigation = true

  [page.repost]
    enable = false
    url = ""

  [page.toc]
    enable = true
    keepStatic = false
    auto = true
    position = "right"
    ordered = false
    startLevel = 2
    endLevel = 6

  [page.expirationReminder]
    enable = false
    reminder = 90
    warning = 180
    closeComment = false

  [page.heading]
    capitalize = false

    [page.heading.number]
      enable = false
      onlyMainSection = true

      [page.heading.number.format]
        h1 = "{title}"
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"

  [page.math]
    enable = true
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    copyTex = true
    mhchem = true

  [page.code]
    enable = true
    copy = true
    edit = true
    maxShownLines = 10

  [page.mapbox]
    accessToken = ""
    lightStyle = "mapbox://styles/mapbox/light-v11"
    darkStyle = "mapbox://styles/mapbox/dark-v11"
    navigation = true
    geolocate = true
    scale = true
    fullscreen = true

  [page.cacheRemoteImages]
    enable = true
    replace = false

  [page.related]
    enable = true
    count = 3

  [page.reward]
    enable = false
    animation = false
    position = "after"
    mode = "static"

  [page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = true
    Pinterest = false
    Tumblr = false
    HackerNews = false
    Reddit = true
    VK = false
    Buffer = false
    Xing = false
    Line = false
    Instapaper = false
    Pocket = false
    Flipboard = false
    Weibo = true
    Myspace = false
    Blogger = false
    Baidu = false
    Odnoklassniki = false
    Evernote = false
    Skype = false
    Trello = false
    Mix = false

  [page.comment]
    enable = true

    [page.comment.artalk]
      enable = false
      server = "https://yourdomain"
      site = "默认站点"
      useBackendConf = false
      placeholder = ""
      noComment = ""
      sendBtn = ""
      editorTravel = true
      flatMode = "auto"
      lightgallery = false
      locale = ""
      emoticons = ""
      nestMax = 2
      nestSort = "DATE_ASC"
      vote = true
      voteDown = false
      uaBadge = true
      listSort = true
      imgUpload = true
      preview = true
      versionCheck = true

    [page.comment.disqus]
      enable = false
      shortname = ""

    [page.comment.gitalk]
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""

    [page.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      placeholder = ""
      avatar = "mp"
      meta = ""
      requiredFields = ""
      pageSize = 10
      lang = ""
      visitor = true
      recordIP = true
      highlight = true
      enableQQ = false
      serverURLs = ""
      emoji = ""
      commentCount = true

    [page.comment.waline]
      enable = false
      serverURL = ""
      pageview = false
      emoji = ["//unpkg.com/@waline/emojis@1.1.0/weibo"]
      meta = ["nick", "mail", "link"]
      requiredMeta = []
      login = "enable"
      wordLimit = 0
      pageSize = 10
      imageUploader = false
      highlighter = false
      comment = false
      texRenderer = false
      search = false
      recaptchaV3Key = ""
      turnstileKey = ""
      reaction = false

    [page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = ""

    [page.comment.telegram]
      enable = true
      siteID = "r5pJ6E5F"
      limit = 5
      height = ""
      color = ""
      colorful = true
      dislikes = true
      outlined = true

    [page.comment.commento]
      enable = false

    [page.comment.utterances]
      enable = false
      repo = ""
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"

    [page.comment.twikoo]
      enable = false
      envId = ""
      region = ""
      path = ""
      visitor = true
      commentCount = true
      lightgallery = false
      katex = false

    [page.comment.giscus]
      enable = true
      repo = "qomarhsn/Blog-Site"
      repoId = "R_kgDOOqaDYQ"
      category = "General"
      categoryId = "DIC_kwDOOqaDYc4CqLK0"
      mapping = "url"
      origin = "https://giscus.app "
      strict = "1"
      term = ""
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "top"
      lang = "en"
      lightTheme = "light"
      darkTheme = "dark"
      lazyLoad = true

  [page.library]
    [page.library.css]

    [page.library.js]

  [page.seo]
    images = []

    [page.seo.publisher]
      name = ""
      logoUrl = ""
